import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { GlobalContextProvider } from '@/context/GlobalContext';

import { Navbar } from '@/components';
import { ProviderConnect } from '@/components/Provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='fr'>
			<body className={`relative ${inter.className}`}>
				<ProviderConnect>
					<GlobalContextProvider>
						<Navbar />
						{children}
					</GlobalContextProvider>
				</ProviderConnect>
			</body>
		</html>
	);
}
